language: python
matrix:
    include:
        - python: 3.3
          env:
            - NUMPY_SPEC='numpy<1.9'
            - SCIPY_SPEC=scipy
            - COVERAGE="no"
        - python: 2.7
          env:
            - NUMPY_SPEC='numpy<1.9'
            - SCIPY_SPEC=scipy
            - COVERAGE="yes"
        - python: 2.6
          env:
            - NUMPY_SPEC='numpy==1.6.2'
            - SCIPY_SPEC='scipy==0.9.0'
            - COVERAGE="no"

before_install:
    - uname -a
    - python -c 'import struct; print(struct.calcsize("P") * 8)'
    - sudo apt-get update -qq
    - sudo apt-get install -qq liblapack-dev libatlas-dev libatlas-base-dev gfortran swig
    - pip install --upgrade pip setuptools pytest pytest-xdist cython
    - pip install --use-wheel six
    - export PIP_CMD='pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel'

install:
    - $PIP_CMD $NUMPY_SPEC
    - $PIP_CMD $SCIPY_SPEC
    - if [ "${COVERAGE}" == "yes" ]; then pip install coverage coveralls; fi

script:
    - if [ "${COVERAGE}" == "yes" ]; then coverage run --source=PyDSTool setup.py test -q; else python setup.py test; fi

after_success:
    - if [ "${COVERAGE}" == "yes" ]; then coveralls; fi

cache: apt
